services:
  - type: web
    name: robotics-telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
